
export const SET_APPUSER_SELECT_VALUE = 'SET_APPUSER_SELECT_VALUE'
export const SET_APPUSER_SEARCH_DATA = 'SET_APPUSER_SEARCH_DATA'
export const SET_APPUSER_CURRENT_PAGE = 'SET_APPUSER_CURRENT_PAGE'
