
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const SET_BUSINESS_ID = 'SET_BUSINESS_ID'
export const SET_USER_SEARCH_DATA = 'SET_USER_SEARCH_DATA'
export const SET_USER_CURRENT_PAGE = 'SET_USER_CURRENT_PAGE'
